"""Generate version info files from Bazel stamp status files.

Usage (invoked by Bazel genrule with stamp = 1):
    python3 gen_version_info.py --format=python \
        --stable=bazel-out/stable-status.txt \
        --volatile=bazel-out/volatile-status.txt \
        --output=_version_info.py

    python3 gen_version_info.py --format=cpp \
        --stable=bazel-out/stable-status.txt \
        --volatile=bazel-out/volatile-status.txt \
        --output=build_version.h
"""

import argparse
import sys


def parse_status_file(path):
    """Parse a Bazel status file into a dict of key-value pairs."""
    result = {}
    try:
        with open(path, "r") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                parts = line.split(" ", 1)
                if len(parts) == 2:
                    result[parts[0]] = parts[1]
                elif len(parts) == 1:
                    result[parts[0]] = ""
    except FileNotFoundError:
        pass
    return result


def generate_python(vars, output):
    version = vars.get("STABLE_KVCM_VERSION", "0.0.0")
    git_commit = vars.get("STABLE_GIT_COMMIT", "unknown")
    git_commit_full = vars.get("STABLE_GIT_COMMIT_FULL", "unknown")
    git_repo = vars.get("STABLE_GIT_REPO", "unknown")
    build_date = vars.get("BUILD_DATE", "unknown")
    build_time = vars.get("BUILD_TIME", "unknown")
    full_version = "%s+%s.%s" % (version, build_date, git_commit)

    with open(output, "w") as f:
        f.write("# Auto-generated by Bazel build. Do not edit.\n")
        f.write('VERSION = "%s"\n' % version)
        f.write('GIT_COMMIT = "%s"\n' % git_commit)
        f.write('GIT_COMMIT_FULL = "%s"\n' % git_commit_full)
        f.write('GIT_REPO = "%s"\n' % git_repo)
        f.write('BUILD_DATE = "%s"\n' % build_date)
        f.write('BUILD_TIME = "%s"\n' % build_time)
        f.write('FULL_VERSION = "%s"\n' % full_version)


def generate_cpp(vars, output):
    version = vars.get("STABLE_KVCM_VERSION", "0.0.0")
    git_commit = vars.get("STABLE_GIT_COMMIT", "unknown")
    git_commit_full = vars.get("STABLE_GIT_COMMIT_FULL", "unknown")
    git_repo = vars.get("STABLE_GIT_REPO", "unknown")
    build_date = vars.get("BUILD_DATE", "unknown")
    build_time = vars.get("BUILD_TIME", "unknown")
    full_version = "%s+%s.%s" % (version, build_date, git_commit)

    with open(output, "w") as f:
        f.write("#pragma once\n")
        f.write("// Auto-generated by Bazel build. Do not edit.\n")
        f.write('#define KVCM_VERSION "%s"\n' % version)
        f.write('#define KVCM_GIT_COMMIT "%s"\n' % git_commit)
        f.write('#define KVCM_GIT_COMMIT_FULL "%s"\n' % git_commit_full)
        f.write('#define KVCM_GIT_REPO "%s"\n' % git_repo)
        f.write('#define KVCM_BUILD_DATE "%s"\n' % build_date)
        f.write('#define KVCM_BUILD_TIME "%s"\n' % build_time)
        f.write('#define KVCM_FULL_VERSION "%s"\n' % full_version)


def main():
    parser = argparse.ArgumentParser(description="Generate version info from Bazel stamp files")
    parser.add_argument("--format", required=True, choices=["python", "cpp"])
    parser.add_argument("--stable", required=True, help="Path to stable-status.txt")
    parser.add_argument("--volatile", required=True, help="Path to volatile-status.txt")
    parser.add_argument("--output", required=True, help="Output file path")
    args = parser.parse_args()

    vars = {}
    vars.update(parse_status_file(args.stable))
    vars.update(parse_status_file(args.volatile))

    if args.format == "python":
        generate_python(vars, args.output)
    elif args.format == "cpp":
        generate_cpp(vars, args.output)


if __name__ == "__main__":
    main()
