package(default_visibility = ["//visibility:public"])

filegroup(
    name = "start_server_script",
    srcs = [
        "start_server.sh",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "start_server_spectrum_script",
    srcs = [
        "start_server_spectrum.sh",
    ],
    visibility = ["//visibility:public"],
)