package(default_visibility = ["//visibility:public"])

cc_library(
    name = "service_discovery_factory_extension",
    srcs = [
        "service_discovery_factory_extension.cc",
    ],
    deps = [
        "//kv_cache_manager/common:service_discovery_factory_extension_api",
    ],
)
