# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: subscriber/proto/kv_cache_group_metadata.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'subscriber/proto/kv_cache_group_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.subscriber/proto/kv_cache_group_metadata.proto\"e\n\x16KvCacheGroupMetadataPB\x12\x11\n\tgroup_idx\x18\x01 \x01(\x05\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x12\n\nblock_size\x18\x03 \x01(\x05\x12\x16\n\x0esliding_window\x18\x04 \x01(\x05\"\x7f\n\x12KvCacheGroupListPB\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.KvCacheGroupMetadataPB\x12\x30\n\x08\x65rr_code\x18\x02 \x01(\x0e\x32\x1e.KvCacheGroupMetadataErrorCode\x12\x0f\n\x07\x65rr_msg\x18\x03 \x01(\t\"\x18\n\x16KvCacheGroupsRequestPB*h\n\x1dKvCacheGroupMetadataErrorCode\x12\x1e\n\x1aKV_CACHE_GROUP_METADATA_OK\x10\x00\x12\'\n#KV_CACHE_GROUP_METADATA_UNAVAILABLE\x10\x01\x32V\n\nRpcService\x12H\n\x18GetKvCacheGroupsMetadata\x12\x17.KvCacheGroupsRequestPB\x1a\x13.KvCacheGroupListPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subscriber.proto.kv_cache_group_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KVCACHEGROUPMETADATAERRORCODE']._serialized_start=308
  _globals['_KVCACHEGROUPMETADATAERRORCODE']._serialized_end=412
  _globals['_KVCACHEGROUPMETADATAPB']._serialized_start=50
  _globals['_KVCACHEGROUPMETADATAPB']._serialized_end=151
  _globals['_KVCACHEGROUPLISTPB']._serialized_start=153
  _globals['_KVCACHEGROUPLISTPB']._serialized_end=280
  _globals['_KVCACHEGROUPSREQUESTPB']._serialized_start=282
  _globals['_KVCACHEGROUPSREQUESTPB']._serialized_end=306
  _globals['_RPCSERVICE']._serialized_start=414
  _globals['_RPCSERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
