# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from subscriber.proto import kv_cache_group_metadata_pb2 as subscriber_dot_proto_dot_kv__cache__group__metadata__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in subscriber/proto/kv_cache_group_metadata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKvCacheGroupsMetadata = channel.unary_unary(
                '/RpcService/GetKvCacheGroupsMetadata',
                request_serializer=subscriber_dot_proto_dot_kv__cache__group__metadata__pb2.KvCacheGroupsRequestPB.SerializeToString,
                response_deserializer=subscriber_dot_proto_dot_kv__cache__group__metadata__pb2.KvCacheGroupListPB.FromString,
                _registered_method=True)


class RpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetKvCacheGroupsMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKvCacheGroupsMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKvCacheGroupsMetadata,
                    request_deserializer=subscriber_dot_proto_dot_kv__cache__group__metadata__pb2.KvCacheGroupsRequestPB.FromString,
                    response_serializer=subscriber_dot_proto_dot_kv__cache__group__metadata__pb2.KvCacheGroupListPB.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetKvCacheGroupsMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RpcService/GetKvCacheGroupsMetadata',
            subscriber_dot_proto_dot_kv__cache__group__metadata__pb2.KvCacheGroupsRequestPB.SerializeToString,
            subscriber_dot_proto_dot_kv__cache__group__metadata__pb2.KvCacheGroupListPB.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
