package(default_visibility = ["//visibility:private"])

cc_test(
    name = "nuraft_smoke_test",
    srcs = ["nuraft_smoke_test.cc"],
    deps = [
        "//kv_cache_manager/common:unittest",
        "@nuraft//:nuraft",
    ],
)
