package(default_visibility = ["//visibility:public"])

cc_library(
    name = "p2p",
    srcs = [
        "tier_global_tracker.cc",
    ],
    hdrs = [
        "tier_global_tracker.h",
    ],
    deps = [
        "//kv_cache_manager/optimizer/tier_flow",
    ],
)
