package(default_visibility = ["//visibility:private"])

cc_binary(
    name = "mock_inference_node",
    srcs = ["mock_inference_node.cc"],
    deps = [
        "//kv_cache_manager/client",
        "//kv_cache_manager/common:logger",
    ],
)
