alog.rootLogger=INFO, benchmarkAppender
alog.max_msg_len=204800

alog.appender.benchmarkAppender=FileAppender
alog.appender.benchmarkAppender.fileName=logs/kv_cache_manager_benchmark_v6d.log
alog.appender.benchmarkAppender.layout=PatternLayout
alog.appender.benchmarkAppender.layout.LogPattern=[%d] [%l] [%p:%t] %m
alog.appender.benchmarkAppender.async_flush=false
alog.appender.benchmarkAppender.flush=true
alog.appender.benchmarkAppender.compress=false
