package(default_visibility = ["//visibility:private"])

cc_test(
    name = "ChecksumVerifyUtilTest",
    srcs = [
        "checksum_verify_util_test.cc",
    ],
    copts = ["-fno-access-control"],
    deps = [
        "//kv_cache_manager/client/src/internal/util",
        "//kv_cache_manager/common:unittest",
    ],
)
