ARG BASE_OS_IMAGE=alibaba-cloud-linux-3-registry.cn-hangzhou.cr.aliyuncs.com/alinux3/alinux3:latest
ARG BAZELISK_VERSION=v1.20.0
ARG BUILDIFIER_VERSION=v8.2.1
ARG BAZELISK_BASE_URL=https://mirrors.huaweicloud.com/bazel/

FROM $BASE_OS_IMAGE
LABEL org.opencontainers.image.source=https://github.com/alibaba/tair-kvcache
LABEL org.opencontainers.image.description="Tair KVCache Manager Dev Container"
LABEL org.opencontainers.image.licenses=Apache-2.0

ARG BAZELISK_VERSION
ARG BUILDIFIER_VERSION
ARG BAZELISK_BASE_URL
ARG TARGETARCH

USER root

# libicu for CLion IDE
# pigz for bazel pkg_tar
# autopep8 buildifier clang-tools-extra(clang-format) for code format
# jemalloc for start_server.sh; valkey for local integration tests
# gdb and file for the CI core-dump backtrace collector
# avoid using internal yum repo
RUN sed -i.bak 's|http://mirrors\.cloud\.aliyuncs\.com|http://mirrors.aliyun.com|g' /etc/yum.repos.d/*.repo && \
    yum install -y --setopt=timeout=3 libicu pigz libibverbs-devel librdmacm-devel numactl-devel  \
    cpio patchelf libaio-devel jemalloc valkey \
    vim gcc gcc-c++ libasan git openssh wget curl jq procps-ng iproute tar clang-tools-extra gdb file \
    python3.11 python3.11-pip python3.11-devel && \
    yum clean all && \
    rm -rf /var/cache/yum

COPY requirements-dev.txt /tmp/requirements-dev.txt
RUN python3.11 -m pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ && \
    python3.11 -m pip install --no-cache-dir -r /tmp/requirements-dev.txt && \
    rm /tmp/requirements-dev.txt

RUN wget "https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-linux-${TARGETARCH}" -O /usr/local/bin/bazelisk && chmod a+x /usr/local/bin/bazelisk && \
    BAZELISK_BASE_URL=$BAZELISK_BASE_URL USE_BAZEL_VERSION=6.4.0 bazelisk && \
    wget "https://github.com/bazelbuild/buildtools/releases/download/${BUILDIFIER_VERSION}/buildifier-linux-${TARGETARCH}" -O /usr/local/bin/buildifier && chmod a+x /usr/local/bin/buildifier


ENV KV_CACHE_MANAGER_DEV_VERSION __IMAGE_VERSION_PLACEHOLDER__
