# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kvcm_meta_minimal.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17kvcm_meta_minimal.proto\x12\x1bkv_cache_manager.proto.meta\"O\n\x06Status\x12\x34\n\x04\x63ode\x18\x01 \x01(\x0e\x32&.kv_cache_manager.proto.meta.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"v\n\x14\x43ommonResponseHeader\x12\x33\n\x06status\x18\x01 \x01(\x0b\x32#.kv_cache_manager.proto.meta.Status\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x15\n\rtracer_result\x18\x03 \x01(\t\"\x1f\n\rBoolMasksType\x12\x0e\n\x06values\x18\x01 \x03(\x08\"g\n\tBlockMask\x12\x10\n\x06offset\x18\x01 \x01(\x05H\x00\x12@\n\nbool_masks\x18\x02 \x01(\x0b\x32*.kv_cache_manager.proto.meta.BoolMasksTypeH\x00\x42\x06\n\x04info\"\x8d\x02\n\x17GetCacheLocationRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x13\n\x0binstance_id\x18\x02 \x01(\t\x12:\n\nquery_type\x18\x03 \x01(\x0e\x32&.kv_cache_manager.proto.meta.QueryType\x12\x12\n\nblock_keys\x18\x04 \x03(\x03\x12\x11\n\ttoken_ids\x18\x05 \x03(\x03\x12:\n\nblock_mask\x18\x06 \x01(\x0b\x32&.kv_cache_manager.proto.meta.BlockMask\x12\x0f\n\x07sw_size\x18\x07 \x01(\x05\x12\x1b\n\x13location_spec_names\x18\x08 \x03(\t\"]\n\x18GetCacheLocationResponse\x12\x41\n\x06header\x18\x01 \x01(\x0b\x32\x31.kv_cache_manager.proto.meta.CommonResponseHeader*$\n\tErrorCode\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x06\n\x02OK\x10\x01*F\n\tQueryType\x12\x12\n\x0eQT_UNSPECIFIED\x10\x00\x12\x10\n\x0cQT_BATCH_GET\x10\x01\x12\x13\n\x0fQT_PREFIX_MATCH\x10\x02\x32\x8e\x01\n\x0bMetaService\x12\x7f\n\x10GetCacheLocation\x12\x34.kv_cache_manager.proto.meta.GetCacheLocationRequest\x1a\x35.kv_cache_manager.proto.meta.GetCacheLocationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvcm_meta_minimal_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ERRORCODE']._serialized_start=762
  _globals['_ERRORCODE']._serialized_end=798
  _globals['_QUERYTYPE']._serialized_start=800
  _globals['_QUERYTYPE']._serialized_end=870
  _globals['_STATUS']._serialized_start=56
  _globals['_STATUS']._serialized_end=135
  _globals['_COMMONRESPONSEHEADER']._serialized_start=137
  _globals['_COMMONRESPONSEHEADER']._serialized_end=255
  _globals['_BOOLMASKSTYPE']._serialized_start=257
  _globals['_BOOLMASKSTYPE']._serialized_end=288
  _globals['_BLOCKMASK']._serialized_start=290
  _globals['_BLOCKMASK']._serialized_end=393
  _globals['_GETCACHELOCATIONREQUEST']._serialized_start=396
  _globals['_GETCACHELOCATIONREQUEST']._serialized_end=665
  _globals['_GETCACHELOCATIONRESPONSE']._serialized_start=667
  _globals['_GETCACHELOCATIONRESPONSE']._serialized_end=760
  _globals['_METASERVICE']._serialized_start=873
  _globals['_METASERVICE']._serialized_end=1015
# @@protoc_insertion_point(module_scope)
