# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kvcm_optimizer_ingest_minimal.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#kvcm_optimizer_ingest_minimal.proto\x12$kv_cache_manager.dashtrace.optimizer\"X\n\x06Status\x12=\n\x04\x63ode\x18\x01 \x01(\x0e\x32/.kv_cache_manager.dashtrace.optimizer.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x7f\n\x14\x43ommonResponseHeader\x12<\n\x06status\x18\x01 \x01(\x0b\x32,.kv_cache_manager.dashtrace.optimizer.Status\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x15\n\rtracer_result\x18\x03 \x01(\t\"\x91\x01\n\x10TraceObservation\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12\x13\n\x0binstance_id\x18\x03 \x01(\t\x12\x11\n\ttoken_ids\x18\x04 \x03(\x03\x12\x14\n\x0ctimestamp_ns\x18\x05 \x01(\x03\x12\x1b\n\x13location_spec_names\x18\x06 \x03(\t\"\x81\x01\n\x1cTraceObservationBatchRequest\x12\x13\n\x0bproducer_id\x18\x01 \x01(\t\x12L\n\x0cobservations\x18\x02 \x03(\x0b\x32\x36.kv_cache_manager.dashtrace.optimizer.TraceObservation\"\xa3\x01\n\x1dTraceObservationBatchResponse\x12J\n\x06header\x18\x01 \x01(\x0b\x32:.kv_cache_manager.dashtrace.optimizer.CommonResponseHeader\x12\x16\n\x0e\x61\x63\x63\x65pted_count\x18\x02 \x01(\x04\x12\x1e\n\x16last_accepted_sequence\x18\x03 \x01(\x04*\xc3\x01\n\tErrorCode\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x0f\n\x0bUNSUPPORTED\x10\x02\x12\x12\n\x0eINTERNAL_ERROR\x10\x03\x12\x15\n\x11SERVICE_NOT_READY\x10\x04\x12\x14\n\x10INVALID_ARGUMENT\x10\x05\x12\x14\n\x10\x44UPLICATE_ENTITY\x10\x06\x12\x1d\n\x19REACH_MAX_ENTITY_CAPACITY\x10\x07\x12\x16\n\x12INSTANCE_NOT_EXIST\x10\x08\x32\xbb\x01\n\x1bOptimizerEventStreamService\x12\x9b\x01\n\x10ReportTraceBatch\x12\x42.kv_cache_manager.dashtrace.optimizer.TraceObservationBatchRequest\x1a\x43.kv_cache_manager.dashtrace.optimizer.TraceObservationBatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvcm_optimizer_ingest_minimal_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ERRORCODE']._serialized_start=743
  _globals['_ERRORCODE']._serialized_end=938
  _globals['_STATUS']._serialized_start=77
  _globals['_STATUS']._serialized_end=165
  _globals['_COMMONRESPONSEHEADER']._serialized_start=167
  _globals['_COMMONRESPONSEHEADER']._serialized_end=294
  _globals['_TRACEOBSERVATION']._serialized_start=297
  _globals['_TRACEOBSERVATION']._serialized_end=442
  _globals['_TRACEOBSERVATIONBATCHREQUEST']._serialized_start=445
  _globals['_TRACEOBSERVATIONBATCHREQUEST']._serialized_end=574
  _globals['_TRACEOBSERVATIONBATCHRESPONSE']._serialized_start=577
  _globals['_TRACEOBSERVATIONBATCHRESPONSE']._serialized_end=740
  _globals['_OPTIMIZEREVENTSTREAMSERVICE']._serialized_start=941
  _globals['_OPTIMIZEREVENTSTREAMSERVICE']._serialized_end=1128
# @@protoc_insertion_point(module_scope)
