package(default_visibility = ["//visibility:public"])

cc_library(
    name = "util",
    srcs = [],
    hdrs = [
        "checksum_verify_util.h",
        "debug_string_util.h",
    ],
    deps = [
        "//kv_cache_manager/common",
    ],
)
